platform :ios, '8.0'
target 'YiJIaStoreApp' do
pod 'AFNetworking'
pod 'SDWebImage'
pod 'SDAutoLayout'
pod 'IQKeyboardManager'
pod 'MJExtension'
pod 'JSONKit'
pod 'AvoidCrash'
pod 'DateTools'
pod 'JSBadgeView'
pod 'ImagePlayerView'
end

